POST /residents/10/birth
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber": 8,
  "birthDeathTypeCode": "출생",
  "reportResidentSerialNumber": 10,
  "birthDeathReportDate": "1998-11-13T00:00:00",
  "birthReportQualificationsCode": "부",
  "emailAddress": "nhn@academy.com",
  "phoneNumber": "010-1234-5678"
}

###

PUT /residents/10/birth/8
Host: localhost:8080
Content-Type: application/json

{
  "emailAddress": "test@test.com",
  "phoneNumber": "010-1234-5678"
}

###

DELETE /residents/10/birth/8
Host: localhost:8080
